Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ces35lab3"
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.provision "shell", path: "provisioner.sh"
  config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
  end
  config.vm.network :private_network, ip: "172.16.2.25"
end
